// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PunchedApi.Infrastructure.Data;

#nullable disable

namespace PunchedApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260831090000_AddProgramFlexibleConfig")]
    partial class AddProgramFlexibleConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PunchedApi.Domain.Entities.LoyaltyProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DefaultEnrollmentStamps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("default_enrollment_stamps");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MaxStampsPerVisit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("max_stamps_per_visit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Loyalty Program")
                        .HasColumnName("name");

                    b.Property<string>("RewardDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reward_description");

                    b.Property<int>("RewardExpirationHours")
                        .HasColumnType("integer")
                        .HasColumnName("reward_expiration_hours");

                    b.Property<decimal>("RewardValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("reward_value");

                    b.Property<int?>("StampExpiryDays")
                        .HasColumnType("integer")
                        .HasColumnName("stamp_expiry_days");

                    b.Property<int>("StampsRequired")
                        .HasColumnType("integer")
                        .HasColumnName("stamps_required");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text")
                        .HasColumnName("config_json");

                    b.Property<string>("Description")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500)
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("ProgramType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("stamp")
                        .HasColumnName("program_type");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("loyalty_programs", null, t =>
                        {
                            t.HasCheckConstraint("chk_program_max_stamps_per_visit_positive", "\"max_stamps_per_visit\" >= 1");

                            t.HasCheckConstraint("chk_program_reward_value_positive", "\"reward_value\" > 0");

                            t.HasCheckConstraint("chk_stamps_required_positive", "\"stamps_required\" > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
